import type { VercelRequest, VercelResponse } from '@vercel/node';
// Import the pre-bundled, self-contained CJS builds (dist/*.cjs) rather than
// the raw TypeScript sources. Vercel's Node.js runtime does not bundle
// extensionless relative TS imports for ESM ("type": "module") functions —
// it transpiles each file 1:1 and leaves the relative import as-is, which
// Node's ESM loader then fails to resolve at runtime
// (ERR_MODULE_NOT_FOUND: Cannot find module '/var/task/server'). The
// dist/*.cjs files are produced by `npm run build` via esbuild --bundle,
// which inlines all local dependencies into a single file, so there is
// nothing left for the runtime to resolve.
// @ts-expect-error - dist/*.cjs is a build artifact generated by esbuild, not source under tsconfig's rootDir.
import { createApp } from '../dist/server.cjs';
// @ts-expect-error - dist/*.cjs is a build artifact generated by esbuild, not source under tsconfig's rootDir.
import { handleSocialCrawler } from '../dist/social-ssr.cjs';

let appPromise: ReturnType<typeof createApp> | undefined;

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Social crawlers must never pass through Vite/SPA middleware first.
  // Render a deterministic HTML head directly from Supabase for rich previews.
  if (await handleSocialCrawler(req, res)) return;

  appPromise ??= createApp();
  const app = await appPromise;
  return app(req, res);
}
